### ISSUE TITLE
Import PEX permissions?

### ISSUE THREAD

**Issue by ricardogottheil** [MrJesseZ/UltraPermissions#1]
Hello MrJesseZ

I saw the video review of Maxmar628 and I liked the plugin, but I have some questions: Can I migrate pex permissions to ultra permissions? or  Do I need to do it manually?

Sincerely.
Ricardo.

**Comment by timokueck** [comment]
Hello!

Im not JesseZ but I the developer of this plugin.
There is no importer available from pex to uperms.

Regards,
Tech

**Comment by ricardogottheil** [comment]
Thank you, TechXcrafter.
